HOSPITALS = [
    {
        "name": "AIIMS New Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "address": "Ansari Nagar, New Delhi",
        "lat": 28.5672,
        "lng": 77.2100,
        "type": "Centre of Excellence (NPRD)",
        "specialties": ["Medical Genetics", "Pediatric Neurology", "Hematology", "Endocrinology"],
        "services": ["Genetic Counseling", "Bone Marrow Transplant", "Enzyme Replacement Therapy"],
        "emergency_services": True,
        "rating": 4.6,
        "phone": "011-26588500",
        "website": "https://www.aiims.edu/",
    },
    {
        "name": "PGIMER Chandigarh",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "address": "Sector 12, Chandigarh",
        "lat": 30.7649,
        "lng": 76.7764,
        "type": "Centre of Excellence (NPRD)",
        "specialties": ["Medical Genetics", "Pediatric Neurology", "Nephrology", "Metabolic Disorders"],
        "services": ["Genetic Counseling", "Dialysis", "Enzyme Replacement Therapy"],
        "emergency_services": True,
        "rating": 4.5,
        "phone": "0172-2747585",
        "website": "https://pgimer.edu.in/",
    },
    {
        "name": "SGPGI Lucknow",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "address": "Raebareli Road, Lucknow",
        "lat": 26.7514,
        "lng": 80.9426,
        "type": "Centre of Excellence (NPRD)",
        "specialties": ["Medical Genetics", "Hematology", "Gastroenterology", "Nephrology"],
        "services": ["Bone Marrow Transplant", "Genetic Counseling", "Liver Transplant"],
        "emergency_services": True,
        "rating": 4.5,
        "phone": "0522-2494000",
        "website": "https://www.sgpgi.ac.in/",
    },
    {
        "name": "Indira Gandhi Institute of Child Health (IGICH)",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Dharmaram College Post, Bengaluru",
        "lat": 12.9279,
        "lng": 77.5619,
        "type": "Centre of Excellence (NPRD)",
        "specialties": ["Pediatric Genetics", "Lysosomal Storage Disorders", "Pediatric Neurology"],
        "services": ["Enzyme Replacement Therapy", "Genetic Counseling", "Newborn Screening"],
        "emergency_services": True,
        "rating": 4.4,
        "phone": "080-22065100",
        "website": "https://igich.karnataka.gov.in/",
    },
    {
        "name": "Christian Medical College (CMC) Vellore",
        "city": "Vellore",
        "state": "Tamil Nadu",
        "address": "IDA Scudder Road, Vellore",
        "lat": 12.9244,
        "lng": 79.1354,
        "type": "Multi-specialty (Private, Trust-run)",
        "specialties": ["Medical Genetics", "Hematology", "Immunology", "Endocrinology"],
        "services": ["Bone Marrow Transplant", "Genetic Counseling", "Immunodeficiency Care"],
        "emergency_services": True,
        "rating": 4.7,
        "phone": "0416-2281000",
        "website": "https://www.cmch-vellore.edu/",
    },
    {
        "name": "Tata Memorial Hospital",
        "city": "Mumbai",
        "state": "Maharashtra",
        "address": "Parel, Mumbai",
        "lat": 19.0022,
        "lng": 72.8426,
        "type": "Government (Cancer Specialty)",
        "specialties": ["Oncology", "Hematology", "Bone Marrow Transplant"],
        "services": ["Bone Marrow Transplant", "Chemotherapy", "Pediatric Oncology"],
        "emergency_services": True,
        "rating": 4.6,
        "phone": "022-24177000",
        "website": "https://tmc.gov.in/",
    },
    {
        "name": "NIMHANS Bengaluru",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Hosur Road, Bengaluru",
        "lat": 12.9432,
        "lng": 77.5946,
        "type": "Government (Neuro Specialty)",
        "specialties": ["Neurology", "Neurogenetics", "Psychiatry"],
        "services": ["Neurological Diagnostics", "Genetic Counseling", "Rehabilitation"],
        "emergency_services": True,
        "rating": 4.5,
        "phone": "080-26995000",
        "website": "https://nimhans.ac.in/",
    },
    {
        "name": "Apollo Hospitals Greams Road",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "address": "Greams Road, Chennai",
        "lat": 13.0604,
        "lng": 80.2496,
        "type": "Multi-specialty (Private)",
        "specialties": ["Medical Genetics", "Cardiology", "Nephrology", "Hematology"],
        "services": ["Organ Transplant", "Genetic Counseling", "24x7 Emergency"],
        "emergency_services": True,
        "rating": 4.5,
        "phone": "044-28296569",
        "website": "https://www.apollohospitals.com/",
    },
    {
        "name": "Narayana Health City",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Bommasandra, Bengaluru",
        "lat": 12.8090,
        "lng": 77.6069,
        "type": "Multi-specialty (Private)",
        "specialties": ["Cardiology", "Hematology", "Pediatric Surgery"],
        "services": ["Bone Marrow Transplant", "24x7 Emergency", "Pediatric ICU"],
        "emergency_services": True,
        "rating": 4.4,
        "phone": "080-71222222",
        "website": "https://www.narayanahealth.org/",
    },
    {
        "name": "Apollo Hospitals Jubilee Hills",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Jubilee Hills, Hyderabad",
        "lat": 17.4239,
        "lng": 78.4738,
        "type": "Multi-specialty (Private)",
        "specialties": ["Medical Genetics", "Endocrinology", "Nephrology"],
        "services": ["Genetic Counseling", "Dialysis", "24x7 Emergency"],
        "emergency_services": True,
        "rating": 4.4,
        "phone": "040-23607777",
        "website": "https://www.apollohospitals.com/",
    },
    {
        "name": "Fortis Memorial Research Institute",
        "city": "Gurugram",
        "state": "Haryana",
        "address": "Sector 44, Gurugram",
        "lat": 28.4646,
        "lng": 77.0870,
        "type": "Multi-specialty (Private)",
        "specialties": ["Hematology", "Oncology", "Neurology"],
        "services": ["Bone Marrow Transplant", "24x7 Emergency", "Pediatric ICU"],
        "emergency_services": True,
        "rating": 4.4,
        "phone": "0124-4962200",
        "website": "https://www.fortishealthcare.com/",
    },
    {
        "name": "Manipal Hospital Old Airport Road",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Old Airport Road, Bengaluru",
        "lat": 12.9581,
        "lng": 77.6482,
        "type": "Multi-specialty (Private)",
        "specialties": ["Medical Genetics", "Pediatrics", "Endocrinology"],
        "services": ["Genetic Counseling", "24x7 Emergency", "NICU"],
        "emergency_services": True,
        "rating": 4.3,
        "phone": "080-25024444",
        "website": "https://www.manipalhospitals.com/",
    },
    {
        "name": "Kokilaben Dhirubhai Ambani Hospital",
        "city": "Mumbai",
        "state": "Maharashtra",
        "address": "Four Bungalows, Andheri West, Mumbai",
        "lat": 19.1334,
        "lng": 72.8267,
        "type": "Multi-specialty (Private)",
        "specialties": ["Medical Genetics", "Neurology", "Hematology"],
        "services": ["Bone Marrow Transplant", "24x7 Emergency", "Genetic Counseling"],
        "emergency_services": True,
        "rating": 4.5,
        "phone": "022-42696969",
        "website": "https://www.kokilabenhospital.com/",
    },
    {
        "name": "KEM Hospital Mumbai",
        "city": "Mumbai",
        "state": "Maharashtra",
        "address": "Parel, Mumbai",
        "lat": 19.0016,
        "lng": 72.8414,
        "type": "Government",
        "specialties": ["Pediatrics", "Hematology", "Nephrology"],
        "services": ["24x7 Emergency", "Dialysis", "Blood Bank"],
        "emergency_services": True,
        "rating": 4.2,
        "phone": "022-24107000",
        "website": "https://www.kem.edu/",
    },
]
